#!/bin/ruby

require "./Parameters.rb"
require "./DisplayProbabilities.rb"
require "./DisplayZ.rb"
require "./DisplayResults.rb"

a, b = Parameters.parseParameters(ARGV)

probs, xLaw, yLaw = DisplayProbabilities.displayProbabilities(a, b)
zLaw = DisplayZ.displayZ(probs)
DisplayResults.displayResults(xLaw, yLaw, zLaw)
